---
- name: Deploy Web App
  hosts: all
  become: true
  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image
      docker_image:
        name: leeshalulu01/webapp
        tag: "1.0"
        source: pull

    - name: Run Docker container
      docker_container:
        name: webapp
        image: leeshalulu01/webapp:1.0
        state: started
        restart_policy: always
        ports:
          - "80:3000"   # Map container port 3000 → EC2 port 80
